from .create_first_columns import crear_columnas_nombres
from .Cl_obj import crear_columnas_Clobj
from .create_simulation_columns import create_simulation_columns
from .alpha import crear_columnas_alpha